#!/usr/bin/env bash
set -euo pipefail

# CHANGELOG.md is GENERATED from git history by scripts/changelog.sh (never
# hand-edited), so it cannot disagree with the log. This pins the exact output on
# throwaway repos: a golden file for the full changelog, then the options.
#
#   changelog.sh                    the whole file: header + one section per release
#                                   tag (vYYYY.MM.DD[.N]), newest first
#   changelog.sh --unreleased       just the commits since the latest tag
#   changelog.sh --next TAG         the whole file with an extra top section TAG, for
#                                   a release PR written before TAG exists
#   changelog.sh --next-tag         the next tag: today's date, then .1, .2 if taken
#
# The date of a section is the date IN THE TAG NAME, not a commit date, so the
# committed file regenerates byte-identically whenever the tag is placed.
# Conventional commit titles are grouped; the repo's automation (version-pin
# bumps, release commits) is summarised or dropped instead of drowning the list.
repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
. "$repo_root/tests/lib.sh"

command -v git >/dev/null 2>&1 || skip 'git not installed'
script="$repo_root/scripts/changelog.sh"
[ -f "$script" ] || { fail 'scripts/changelog.sh is missing'; finish; }

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
: >"$tmp/gitconfig"
export GIT_CONFIG_GLOBAL="$tmp/gitconfig" GIT_CONFIG_NOSYSTEM=1 GIT_CEILING_DIRECTORIES="$tmp"
export CHANGELOG_REPO_URL='https://example.test/r'

g() { git -C "$1" -c user.name=t -c user.email=t@example.com -c commit.gpgsign=false -c tag.gpgsign=false "${@:2}"; }
c() { g "$1" commit -q --allow-empty -m "$2"; }
run() { (cd "$1" && shift && bash "$script" "$@"); }
pr() { printf '([#%s](%s/pull/%s))' "$1" "$CHANGELOG_REPO_URL" "$1"; }

# A repo with a pre-baseline commit, a baseline tag, a busy release, and its tag.
repo="$tmp/repo"
mkdir -p "$repo"
git -C "$repo" init -q -b main
c "$repo" 'initial commit'
g "$repo" tag -a v2026.10.02 -m baseline
c "$repo" 'feat(devtmp): one folder for build output (#234)'
c "$repo" 'fix(opencode)!: converge MCP entries on the catalog (#239)'
c "$repo" 'fix: a plain fix with no scope (#241)'
c "$repo" 'docs(windows): python3 on Windows (#235)'
c "$repo" 'test(eol): enforce the line-ending policy (#236)'
c "$repo" 'ci: add a job'
c "$repo" 'refactor(doctor): tidy the checks (#242)'
c "$repo" 'chore: auto-update software versions (#237)'
c "$repo" 'chore(guardrail): pin v0.23.34-dev (#243)'
c "$repo" 'chore(deps): bump something (#244)'
c "$repo" 'chore(release): v2026.10.04'
c "$repo" 'something without a conventional prefix (#245)'
g "$repo" tag -a v2026.10.04 -m release

header='# Changelog

Every release of this repo, newest first. Generated by `scripts/changelog.sh`
from git history - do not edit by hand (see docs/versioning.md). Versions are
dates: `vYYYY.MM.DD`, with `.1`, `.2` for a second release the same day.'

release_section() {
    cat <<EOF
## v2026.10.04 - 2026-10-04

### Breaking

- **opencode:** converge MCP entries on the catalog $(pr 239)

### Features

- **devtmp:** one folder for build output $(pr 234)

### Fixes

- a plain fix with no scope $(pr 241)

### Documentation

- **windows:** python3 on Windows $(pr 235)

### Tests and CI

- add a job
- **eol:** enforce the line-ending policy $(pr 236)

### Refactoring

- **doctor:** tidy the checks $(pr 242)

### Maintenance

- **deps:** bump something $(pr 244)
- 2 automated version-pin updates

### Other

- something without a conventional prefix $(pr 245)
EOF
}
baseline_section='## v2026.10.02 - 2026-10-02

Baseline: the first tagged state. Earlier history is in `git log`.'

# 1. The golden file.
want="$(printf '%s\n\n%s\n\n%s\n' "$header" "$(release_section)" "$baseline_section")"
got="$(run "$repo")"
if [ "$got" = "$want" ]; then pass; else
    fail "the full changelog differs from the golden file:$(diff <(printf '%s\n' "$want") <(printf '%s\n' "$got") | head -20)"
fi
# Deterministic: a second run is byte-identical.
[ "$(run "$repo")" = "$got" ] || fail 'two runs must give byte-identical output'
# The pre-baseline commit and the dropped automation never appear.
! grep -Fq 'initial commit' <<<"$got" || fail 'history before the baseline tag must not be listed'
! grep -Fq 'auto-update software versions' <<<"$got" || fail 'bot version bumps must be summarised, not listed'
! grep -Fq 'chore(release)' <<<"$got" || fail 'release commits must be dropped'

# 1b. --section TAG: one existing release's section, exactly as it appears in the file
#     (what the committed-file drift check compares against).
[ "$(run "$repo" --section v2026.10.04)" = "$(release_section)" ] || fail "--section of a release differs: $(run "$repo" --section v2026.10.04 | head -5)"
[ "$(run "$repo" --section v2026.10.02)" = "$baseline_section" ] || fail "--section of the baseline differs: $(run "$repo" --section v2026.10.02)"
if (cd "$repo" && bash "$script" --section v2026.01.01 >/dev/null 2>&1); then fail '--section of a tag that does not exist must be refused'; fi

# 2. --unreleased: only what came after the latest tag.
c "$repo" 'feat(version): after the release (#246)'
want_unrel="$(printf '## Unreleased\n\n### Features\n\n- **version:** after the release %s\n' "$(pr 246)")"
[ "$(run "$repo" --unreleased)" = "$want_unrel" ] || fail "--unreleased wrong: $(run "$repo" --unreleased)"

# 3. --next TAG: a top section for the not-yet-existing tag, the rest unchanged.
want_next="$(printf '%s\n\n## v2026.10.05 - 2026-10-05\n\n### Features\n\n- **version:** after the release %s\n\n%s\n\n%s\n' "$header" "$(pr 246)" "$(release_section)" "$baseline_section")"
[ "$(run "$repo" --next v2026.10.05)" = "$want_next" ] || fail "--next wrong: $(diff <(printf '%s\n' "$want_next") <(run "$repo" --next v2026.10.05) | head -10)"

# 4. --next refuses a bad tag, an old tag, a taken tag, and an empty release.
for bad in foo v2026.10.04 v2026.10.03 v26.10.05; do
    if (cd "$repo" && bash "$script" --next "$bad" >/dev/null 2>&1); then fail "--next $bad must be refused"; fi
done
empty="$tmp/empty"
git clone -q "$repo" "$empty" 2>/dev/null
g "$empty" checkout -q v2026.10.04
if (cd "$empty" && bash "$script" --next v2026.10.05 >/dev/null 2>"$tmp/err"); then
    fail '--next with nothing since the last tag must be refused'
else
    grep -Fqi 'nothing' "$tmp/err" || fail "the empty-release refusal must say so (got: $(cat "$tmp/err"))"
fi

# 5. --next-tag: today, then .1, .2 when the day is taken.
[ "$(CHANGELOG_TODAY=2026-10-05 run "$repo" --next-tag)" = 'v2026.10.05' ] || fail '--next-tag: a fresh day gets vYYYY.MM.DD'
[ "$(CHANGELOG_TODAY=2026-10-04 run "$repo" --next-tag)" = 'v2026.10.04.1' ] || fail '--next-tag: a taken day gets .1'
g "$repo" tag -a v2026.10.04.1 -m again
[ "$(CHANGELOG_TODAY=2026-10-04 run "$repo" --next-tag)" = 'v2026.10.04.2' ] || fail '--next-tag: then .2'
# The .1 tag sorts after the plain one: the ranges stay correct.
grep -Fq '## v2026.10.04.1 - 2026-10-04' <<<"$(run "$repo")" || fail 'a same-day .1 release must get its own section'

# 6. No tags at all.
none="$tmp/none"
mkdir -p "$none"
git -C "$none" init -q -b main
c "$none" 'feat: first thing (#1)'
[ "$(run "$none")" = "$(printf '%s\n\nNo releases yet.' "$header")" ] || fail "a repo with no tags: $(run "$none")"
[ "$(CHANGELOG_TODAY=2026-10-05 run "$none" --next-tag)" = 'v2026.10.05' ] || fail '--next-tag works with no tags'
grep -Fq 'first thing' <<<"$(run "$none" --unreleased)" || fail '--unreleased with no tags lists everything'

# 7. Without a repo URL the PR reference is plain text (no broken link).
c "$repo" 'feat(x): a plain reference (#247)'
plain="$(cd "$repo" && CHANGELOG_REPO_URL='' bash "$script" --unreleased 2>&1)"
grep -Fq 'a plain reference (#247)' <<<"$plain" || fail "without a URL the reference must stay plain: $plain"

# 8. Without CHANGELOG_REPO_URL the link base comes from the origin remote,
#    including an SSH host alias (this repo's remote is git@github-CtrlCarlitos:...).
git -C "$repo" remote add origin 'git@github-alias:Some-Owner/Some-Repo.git'
derived="$(cd "$repo" && env -u CHANGELOG_REPO_URL bash "$script" --unreleased 2>&1)"
grep -Fq '([#247](https://github.com/Some-Owner/Some-Repo/pull/247))' <<<"$derived" ||
    fail "the PR link base must be derived from the origin remote: $derived"

finish
