#Requires -Version 5.1
<#
init-line-endings.ps1 - Windows twin of scripts/init-line-endings.sh.
Gives any repo a complete, mutually-agreeing .gitattributes + .editorconfig
pair from what the repo actually contains. Policy: .gitattributes is the
single line-ending authority, core.autocrlf false everywhere.

Usage: init-line-endings.ps1 [-Force] [[-RepoDir] <path>]   (default: cwd)

Behavior (mirrors the .sh twin):
  - scans tracked files (git ls-files; falls back to Get-ChildItem)
  - writes .gitattributes: `* text=auto eol=lf` default, explicit LF for
    shell types, CRLF for Windows-native scripts, `binary` for binary types
  - writes a matching .editorconfig (utf-8, lf, trim trailing, CRLF for ps1/ps1.tmpl/bat/cmd)
  - runs `git add --renormalize .` in a git repo and reports the count
  - idempotent: existing files are NOT overwritten without -Force
#>
param(
    [switch]$Force,
    [string]$RepoDir = (Get-Location).Path
)

$ErrorActionPreference = 'Stop'

# Cross-generation PSModulePath guard (same class as the other Windows
# scripts in this repo - Get-ChildItem/Out-File live in Management/Utility).
if ($PSVersionTable.PSVersion.Major -le 5) {
    $env:PSModulePath = (($env:PSModulePath -split ';') |
        Where-Object { $_ -and ($_ -notmatch '\\PowerShell\\[67]\\') }) -join ';'
    Import-Module Microsoft.PowerShell.Management, Microsoft.PowerShell.Utility -ErrorAction SilentlyContinue
}

if (-not (Test-Path -LiteralPath $RepoDir -PathType Container)) {
    Write-Error "init-line-endings: no such directory: $RepoDir"
}
Set-Location -LiteralPath $RepoDir

$isGit = $true
try { git rev-parse --is-inside-work-tree *> $null; if ($LASTEXITCODE -ne 0) { $isGit = $false } } catch { $isGit = $false }

if ($isGit) {
    $files = @(git ls-files)
} else {
    $files = @(Get-ChildItem -Recurse -File | Where-Object { $_.FullName -notmatch '\\\.git\\' } | ForEach-Object { $_.FullName.Substring($PWD.Path.Length + 1) })
}
$exts = @($files | ForEach-Object { [IO.Path]::GetExtension($_).TrimStart('.').ToLower() } | Sort-Object -Unique)

function Test-Ext([string]$e) { $exts -contains $e }

# --- .gitattributes ----------------------------------------------------------

$ga = Join-Path $RepoDir '.gitattributes'
if ((Test-Path $ga) -and -not $Force) {
    Write-Host "  .gitattributes exists - keeping (re-run with -Force to overwrite)"
} else {
    $lines = @(
        '# Line-ending policy - the single repo-level authority',
        '# (core.autocrlf should be false; this file decides).',
        "# Generated by init-line-endings$(if ($Force) { ' --force' }).",
        '',
        '* text=auto eol=lf',
        ''
    )
    $shellRules = @('sh', 'bash', 'zsh') | Where-Object { Test-Ext $_ } | ForEach-Object { "*.$_ text eol=lf" }
    if ($shellRules) { $lines += @('# POSIX shell scripts - CRLF breaks them under bash/sh.') + $shellRules + @('') }
    $winRules = @('ps1', 'bat', 'cmd') | Where-Object { Test-Ext $_ } | ForEach-Object { "*.$_ text eol=crlf" }
    if ($winRules) { $lines += @('# Windows-native scripts - CRLF on checkout (LF in the repo).') + $winRules + @('') }
    $lines += @('*.ps1.tmpl text eol=crlf', '*.sh.tmpl text eol=lf', '')
    $binRules = @('png','jpg','jpeg','gif','ico','icns','exe','dll','so','dylib','zip','tar','gz','7z','pdf','woff','woff2','ttf','otf') |
        Where-Object { Test-Ext $_ } | ForEach-Object { "*.$_ binary" }
    if ($binRules) { $lines += @('# Binaries - never normalize.') + $binRules }
    [IO.File]::WriteAllText($ga, ($lines -join "`n") + "`n", (New-Object Text.UTF8Encoding($false)))
    Write-Host "  wrote .gitattributes"
}

# --- .editorconfig -----------------------------------------------------------

$ec = Join-Path $RepoDir '.editorconfig'
if ((Test-Path $ec) -and -not $Force) {
    Write-Host "  .editorconfig exists - keeping (re-run with -Force to overwrite)"
} else {
    $lines = @(
        '# Editor behavior matching .gitattributes.',
        "# Generated by init-line-endings$(if ($Force) { ' --force' }).",
        '',
        'root = true',
        '',
        '[*]',
        'charset = utf-8',
        'end_of_line = lf',
        'insert_final_newline = true',
        'trim_trailing_whitespace = true'
    )
    foreach ($e in @('sh', 'bash', 'zsh', 'py', 'lua')) {
        if (Test-Ext $e) {
            $lines += @('', "[*.$e]", 'indent_style = space', 'indent_size = 4')
        }
    }
    $two = @('yml', 'yaml', 'json', 'md') | Where-Object { Test-Ext $_ } | ForEach-Object { "*.$_" }
    if ($two) {
        # Concat outside the literal: inside @(...), pwsh splits bare
        # `+`-chains into separate elements, which would emit the section
        # header as three lines.
        $twoSection = '[' + ($two -join ',') + ']'
        $lines += @('', $twoSection, 'indent_style = space', 'indent_size = 2')
    }
    if (Test-Ext 'go') { $lines += @('', '[*.go]', 'indent_style = tab') }
    # ps1 and its .tmpl twin share one CRLF rule: EditorConfig globs match
    # the full name, so x.ps1.tmpl needs its own pattern (mirrors .gitattributes).
    $win = @()
    if (Test-Ext 'ps1') { $win += '*.{ps1,ps1.tmpl}' }
    foreach ($e in @('bat', 'cmd')) { if (Test-Ext $e) { $win += "*.$e" } }
    if ($win) {
        $winSection = '[' + ($win -join ',') + ']'
        $lines += @('', '# Windows-native scripts: CRLF here and in .gitattributes.', $winSection, 'end_of_line = crlf', 'indent_style = space', 'indent_size = 4')
    }
    [IO.File]::WriteAllText($ec, ($lines -join "`n") + "`n", (New-Object Text.UTF8Encoding($false)))
    Write-Host "  wrote .editorconfig"
}

# --- renormalize --------------------------------------------------------------

if ($isGit) {
    git add --renormalize . *> $null
    if ($LASTEXITCODE -eq 0) {
        $n = @(git diff --cached --numstat).Count
        if ($n -gt 0) {
            Write-Host "  renormalized: $n file(s) staged with line-ending fixes - review and commit"
        } else {
            Write-Host '  renormalize: repo already consistent (nothing staged)'
        }
    }
} else {
    Write-Host '  not a git repo - skipped renormalize'
}
