#!/usr/bin/env bash
set -euo pipefail

# init-line-endings.sh - give any repo a complete, mutually-agreeing
# .gitattributes + .editorconfig pair, deterministically, from what the repo
# actually contains. Born from the dotfiles/agent-guardrails cross-platform
# (WSL + Windows native) policy: .gitattributes is the single line-ending
# authority, core.autocrlf false everywhere.
#
# Usage: init-line-endings.sh [--force] [repo-dir]   (default: cwd)
#
# Behavior:
#   - scans tracked files (git ls-files; falls back to find) for extensions
#   - writes .gitattributes: `* text=auto eol=lf` default, explicit LF for
#     shell types, CRLF for Windows-native scripts, `binary` for binary types
#   - writes a matching .editorconfig (utf-8, lf, trim trailing, CRLF for
#     ps1/ps1.tmpl/bat/cmd)
#   - runs `git add --renormalize .` in a git repo and reports the count
#   - idempotent: existing files are NOT overwritten without --force

FORCE=false
REPO_DIR="$(pwd)"
for arg in "$@"; do
    case "$arg" in
    --force) FORCE=true ;;
    -h|--help) sed -n '3,18p' "$0"; exit 0 ;;
    *) REPO_DIR="$arg" ;;
    esac
done

[ -d "$REPO_DIR" ] || { echo "init-line-endings: no such directory: $REPO_DIR" >&2; exit 1; }
cd "$REPO_DIR"

# Present extensions (lowercased), one per line.
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    FILES="$(git ls-files)"
else
    FILES="$(find . -type f -not -path './.git/*')"
fi
EXTS="$(printf '%s\n' "$FILES" | sed 's/.*\.//' | tr '[:upper:]' '[:lower:]' | sort -u)"

has() { printf '%s\n' "$EXTS" | grep -Fxq "$1"; }

# --- .gitattributes ----------------------------------------------------------

GA=.gitattributes
if [ -f "$GA" ] && [ "$FORCE" = false ]; then
    echo "  $GA exists - keeping (re-run with --force to overwrite)"
else
    {
        echo "# Line-ending policy - the single repo-level authority"
        echo "# (core.autocrlf should be false; this file decides)."
        echo "# Generated by init-line-endings$( [ "$FORCE" = true ] && echo ' --force' )."
        echo
        echo "* text=auto eol=lf"
        echo
        echo "# POSIX shell scripts - CRLF breaks them under bash/sh."
        for ext in sh bash zsh; do
            has "$ext" && echo "*.$ext text eol=lf"
        done
        echo
        echo "# Windows-native scripts - CRLF on checkout (LF in the repo)."
        for ext in ps1 bat cmd; do
            has "$ext" && echo "*.$ext text eol=crlf"
        done
        echo "*.ps1.tmpl text eol=crlf"
        echo "*.sh.tmpl text eol=lf"
        echo
        echo "# Binaries - never normalize."
        for ext in png jpg jpeg gif ico icns exe dll so dylib zip tar gz 7z pdf woff woff2 ttf otf; do
            has "$ext" && echo "*.$ext binary"
        done
    } > "$GA"
    echo "  wrote $GA"
fi

# --- .editorconfig -----------------------------------------------------------

EC=.editorconfig
if [ -f "$EC" ] && [ "$FORCE" = false ]; then
    echo "  $EC exists - keeping (re-run with --force to overwrite)"
else
    {
        echo "# Editor behavior matching .gitattributes."
        echo "# Generated by init-line-endings$( [ "$FORCE" = true ] && echo ' --force' )."
        echo
        echo "root = true"
        echo
        echo "[*]"
        echo "charset = utf-8"
        echo "end_of_line = lf"
        echo "insert_final_newline = true"
        echo "trim_trailing_whitespace = true"
        for ext in sh bash zsh py lua; do
            if has "$ext"; then
                echo
                echo "[*.$ext]"
                echo "indent_style = space"
                echo "indent_size = 4"
            fi
        done
        if has yml || has yaml || has json || has md; then
            echo
            sect=""
            has yml && sect="*.yml"
            has yaml && sect="${sect:+$sect,}*.yaml"
            has json && sect="${sect:+$sect,}*.json"
            has md && sect="${sect:+$sect,}*.md"
            echo "[${sect}]"
            echo "indent_style = space"
            echo "indent_size = 2"
        fi
        if has go; then
            echo
            echo "[*.go]"
            echo "indent_style = tab"
        fi
        if has ps1 || has bat || has cmd; then
            echo
            echo "# Windows-native scripts: CRLF here and in .gitattributes."
            sect=""
            has ps1 && sect="*.{ps1,ps1.tmpl}"
            has bat && sect="${sect:+$sect,}*.bat"
            has cmd && sect="${sect:+$sect,}*.cmd"
            echo "[${sect}]"
            echo "end_of_line = crlf"
            echo "indent_style = space"
            echo "indent_size = 4"
        fi
    } > "$EC"
    echo "  wrote $EC"
fi

# --- renormalize --------------------------------------------------------------

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git add --renormalize . 2>/dev/null || true
    n="$(git diff --cached --numstat 2>/dev/null | wc -l | tr -d ' ')"
    if [ "$n" -gt 0 ]; then
        echo "  renormalized: $n file(s) staged with line-ending fixes - review and commit"
    else
        echo "  renormalize: repo already consistent (nothing staged)"
    fi
else
    echo "  not a git repo - skipped renormalize"
fi
