#!/usr/bin/env bash
# release.sh - cut a release of this repo in two human-reviewed steps.
# Tags are dates (vYYYY.MM.DD, then .1, .2 for a second release the same day);
# CHANGELOG.md is generated by changelog.sh. See docs/versioning.md.
#
#   release.sh prepare [TAG] [--dry-run]
#       On a branch fresh from origin/main (git switch -c chore/release origin/main):
#       choose the next tag (default: today) and write CHANGELOG.md with a top
#       section for it. Then: git add CHANGELOG.md, commit it as
#       `chore(release): TAG`, open the PR, merge it. Creates no tag.
#
#   release.sh publish TAG [--dry-run]
#       After that PR is merged: tag THE RELEASE COMMIT on origin/main (annotated),
#       push the tag, and create the GitHub Release with the changelog section as
#       its notes. The tag goes on the release commit, not on HEAD: the version-pin
#       bot lands commits on main right after a merge, and a tag on HEAD would then
#       list commits CHANGELOG.md does not. --dry-run checks everything and prints
#       the plan without tagging, pushing or calling gh.
#
# Publishing is outward-facing (a pushed tag and a public release): run it
# deliberately. tests/release_contract.sh runs it against a bare origin.
set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
changelog="$here/changelog.sh"
calver_re='^v[0-9]{4}\.[0-9]{2}\.[0-9]{2}(\.[0-9]+)?$'

die() { printf 'release.sh: %s\n' "$1" >&2; exit 1; }

cmd="${1:-}"
[ "$#" -eq 0 ] || shift
tag='' dry=''
for arg in "$@"; do
    case "$arg" in
        --dry-run) dry=1 ;;
        -*) die "unknown option: $arg" ;;
        *) [ -z "$tag" ] || die "unexpected argument: $arg"; tag="$arg" ;;
    esac
done

git rev-parse --git-dir >/dev/null 2>&1 || die 'not inside a git repository'
cd "$(git rev-parse --show-toplevel)"

case "$cmd" in
    prepare)
        if ! git diff --quiet || ! git diff --cached --quiet; then
            die 'tracked files have uncommitted changes: commit or stash them first'
        fi
        git fetch -q origin
        [ "$(git rev-parse HEAD)" = "$(git rev-parse origin/main)" ] ||
            die 'HEAD is not origin/main: start the release branch from it (git switch -c chore/release origin/main)'
        [ -n "$tag" ] || tag="$(bash "$changelog" --next-tag)"
        content="$(bash "$changelog" --next "$tag")" || exit 1
        latest="$(git tag --list 'v[0-9][0-9][0-9][0-9].*' --sort=v:refname | tail -n 1)"
        count="$(git rev-list --count --no-merges "${latest:+$latest..}HEAD")"
        if [ -n "$dry" ]; then
            printf 'would write CHANGELOG.md with a section for %s (%s commits since %s)\n' "$tag" "$count" "${latest:-the start}"
            exit 0
        fi
        printf '%s\n' "$content" >CHANGELOG.md
        printf 'Wrote CHANGELOG.md with a section for %s (%s commits since %s).\n' "$tag" "$count" "${latest:-the start}"
        printf 'Next: review it, then\n'
        printf '  git add CHANGELOG.md && git commit -m "chore(release): %s"\n' "$tag"
        printf '  open the PR, merge it, then: scripts/release.sh publish %s\n' "$tag"
        ;;

    publish)
        [ -n "$tag" ] || die 'usage: release.sh publish TAG [--dry-run]'
        [[ $tag =~ $calver_re ]] || die "$tag is not a release tag (want vYYYY.MM.DD[.N])"
        git fetch -q origin
        if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then die "tag $tag already exists locally"; fi
        if [ -n "$(git ls-remote --tags origin "refs/tags/$tag")" ]; then die "tag $tag already exists on origin"; fi

        release_sha="$(git log origin/main -n 1 --format=%H --grep="^chore(release): $tag" || true)"
        [ -n "$release_sha" ] || die "no 'chore(release): $tag' commit on origin/main: merge the release PR first"

        top="$(git show "$release_sha:CHANGELOG.md" 2>/dev/null | grep -m 1 '^## ' || true)"
        case "$top" in
            "## $tag - "*) ;;
            *) die "CHANGELOG.md at the release commit does not start with a $tag section (found: ${top:-nothing})" ;;
        esac

        notes="$(mktemp)"
        trap 'rm -f "$notes"' EXIT
        # The section body: everything after the first heading up to the next one.
        git show "$release_sha:CHANGELOG.md" | awk '/^## /{n++; next} n==1' | sed '/./,$!d' >"$notes"

        short="$(git rev-parse --short=7 "$release_sha")"
        if [ -n "$dry" ]; then
            printf 'would tag %s at the release commit %s, push the tag to origin, and run:\n' "$tag" "$short"
            printf '  gh release create %s --title %s --notes-file <the %s section> --verify-tag\n' "$tag" "$tag" "$tag"
            exit 0
        fi
        command -v gh >/dev/null 2>&1 || die 'gh (GitHub CLI) is required to create the release'
        git tag -a "$tag" "$release_sha" -m "Release $tag"
        git push origin "refs/tags/$tag"
        if ! gh release create "$tag" --title "$tag" --notes-file "$notes" --verify-tag; then
            printf 'release.sh: the tag %s is pushed but the GitHub Release failed; retry:\n' "$tag" >&2
            printf '  gh release create %s --title %s --notes-file <section> --verify-tag\n' "$tag" "$tag" >&2
            exit 1
        fi
        printf 'Released %s at %s.\n' "$tag" "$short"
        ;;

    *)
        sed -n '2,/^set -euo/p' "$0" | sed '$d; s/^# \{0,1\}//'
        [ -z "$cmd" ] || [ "$cmd" = -h ] || [ "$cmd" = --help ] || exit 1
        ;;
esac
